version: "2"
services:
  web:
    build: chat-api
    ports:
      - "3000:3000"
    links:
      - mongo
  angular:
    build: client
    ports:
      - "4200:4200"

  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"